Update my_pipeline.yaml

diff --git a/.github/workflows/my_pipeline.yaml b/.github/workflows/my_pipeline.yaml
--- a/.github/workflows/my_pipeline.yaml
+++ b/.github/workflows/my_pipeline.yaml
@@ -1,10 +1,19 @@
 name: Manual Setup - Terraform & Ansible
 
 on:
-  workflow_dispatch:  # Only run manually from the GitHub Actions UI
-  
+  workflow_dispatch:
+    inputs:
+      terraform_action:
+        description: 'Select Terraform Action'
+        required: true
+        default: 'apply'
+        type: choice
+        options:
+          - apply
+          - destroy
+
 permissions:
-  id-token: write   # This is required for requesting the JWT
+  id-token: write
 
 jobs:
   setup:
@@ -17,26 +26,73 @@ jobs:
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v3
         with:
-          terraform_version: 1.12.2 
+          terraform_version: 1.12.2
 
       - name: Show Terraform version
         run: terraform -version
-
-      # - name: Install Ansible
-      #   run: |
-      #     sudo apt update
-      #     sudo apt install -y ansible
-
-      # - name: Show Ansible version
-      #   run: ansible --version
 
       - name: Configure AWS credentials (Use Open ID Connect)
         uses: aws-actions/configure-aws-credentials@v4.1.0
         with:
           role-to-assume: arn:aws:iam::975050221465:role/msd-tech-assignment-aws-role
           aws-region: ap-south-1
+
+      - name: Terraform Init
+        working-directory: ./terraform
+        run: terraform init
+
+      - name: Run Terraform Apply or Destroy
+        working-directory: ./terraform
+        run: |
+          if [ "${{ github.event.inputs.terraform_action }}" == "apply" ]; then
+            terraform apply -auto-approve
+          elif [ "${{ github.event.inputs.terraform_action }}" == "destroy" ]; then
+            terraform destroy -auto-approve
+          else
+            echo "Invalid action: ${{ github.event.inputs.terraform_action }}"
+            exit 1
+          fi
+
+
+# name: Manual Setup - Terraform & Ansible
+
+# on:
+#   workflow_dispatch:  # Only run manually from the GitHub Actions UI
+  
+# permissions:
+#   id-token: write   # This is required for requesting the JWT
+
+# jobs:
+#   setup:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v4
+
+#       - name: Install Terraform
+#         uses: hashicorp/setup-terraform@v3
+#         with:
+#           terraform_version: 1.12.2 
+
+#       - name: Show Terraform version
+#         run: terraform -version
+
+#       # - name: Install Ansible
+#       #   run: |
+#       #     sudo apt update
+#       #     sudo apt install -y ansible
+
+#       # - name: Show Ansible version
+#       #   run: ansible --version
+
+#       - name: Configure AWS credentials (Use Open ID Connect)
+#         uses: aws-actions/configure-aws-credentials@v4.1.0
+#         with:
+#           role-to-assume: arn:aws:iam::975050221465:role/msd-tech-assignment-aws-role
+#           aws-region: ap-south-1
           
 
-      - name: Apply Terraform
-        working-directory: ./terraform
-        run: terraform init && terraform apply -auto-approve
+#       - name: Apply Terraform
+#         working-directory: ./terraform
+#         run: terraform init && terraform apply -auto-approve
